### ISSUE TITLE
Allow user to enter a list in nodes widgets

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#38]
Hi,
connecting MakeRanege to NumberInput results in a "\<List\>". Without wire user is unable to enter a list in a widget.
Plus: disconnecting the wire keep this "\<list\>" string but results in a error.

**Comment by j8sr0230** [comment]
@j8sr0230 Fixed with [https://github.com/j8sr0230/fc_nodes/commit/df804204eb13d1b64863c0e1fcafc241c9af0b1c](https://github.com/j8sr0230/fc_nodes/commit/df804204eb13d1b64863c0e1fcafc241c9af0b1c) by hiding the input widget when the corresponding socket is connected. When the socket becomes free again, the input value is reset to the last value.

The input of lists in the Number Input node should not be possible, but should be realized via other nodes (e.g. Make Range). If a list is connected to the Number Input node, only the first list element is evaluated for reasons of error prevention.

![widget_value_issue](https://user-images.githubusercontent.com/39261150/194014921-b7e902c0-fc26-422a-8cfa-eb079065bd6d.png)
