### ISSUE TITLE
Unable to delete a node if mouse is over

### ISSUE THREAD

**Issue by FlachyJoe** [j8sr0230/fc_nodes#52]
Is the delete key captured by the node and not by the editor?
\+ the node context menu could have a delete entry.

**Comment by j8sr0230** [comment]
@FlachyJoe This was a tricky bug. The new NodeSearchBox has grabbed keyboard input after its initialization with the line 
`self.search_input_widget.grabKeyboard()`
 and as a consequence prevented/blocked all other keyboard inputs such as STR, DEL or ALT. Fixed with [https://github.com/j8sr0230/fc_nodes/commit/e69ee9df68dc5fc71930c00dec2f3bfdd628969a](https://github.com/j8sr0230/fc_nodes/commit/e69ee9df68dc5fc71930c00dec2f3bfdd628969a).
